// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 默认使用项目内本地 SQLite，无需任何外部服务即可运行
    url: process.env["DATABASE_URL"] ?? "file:./prisma/dev.db",
  },
});
